name: prd build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Merge & Push
        run: |
          git remote set-head origin --auto
          git merge "origin/$(git symbolic-ref refs/remotes/origin/HEAD | awk -F'[/]' '{print $NF}')"
          git push

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          SLACK_USERNAME: GitHubBot
          SLACK_TITLE: Commit merge failure!
          SLACK_MESSAGE: ${{ toJSON(needs.merge.outputs) }}
